config/routes.rb
Rails.application.routes.draw do
  # HOME ROUTES
  get 'home/getAllUsers'
  get 'auth/form' => 'auth#form'

  # REGISTER ROUTES
  get 'auth/register' => 'auth#register'
  post 'auth/create' => 'auth#createUser'

  # LOGIN ROUTES
  get 'auth/login' => 'auth#login'
  post 'auth/verifyLogin' => 'auth#verifyLogin'

  # LOGGED / LOG-OUT ROUTES
  get 'home/logged' => 'home#logged'
  post 'auth/logout' => 'auth#logout'

  # =========================================================
  get "up" => "rails/health#show", as: :rails_health_check
  # =========================================================

  get "/fichestats", to: 'fichestats#index'
  get "/perso"  => 'characters#index'

  get "/battle", to: 'battle#index'
  # Route permettant de séléctionner notre character
  post "/select_perso" => 'characters#select'

  #Route permettant de créer un character
  get "/create_character" => 'characters#create_character'
  
  #Route permettant de mettre à jour l'image du character à afficher
  post "create_character_src" => 'characters#insert_character'

  #Route permettant de supprimer un character
  post "/delete_character" => 'characters#delete_character'

  #Route permettant de rentrer dans le jeu avec un character séléctionné
  post "/playing/enterWorld" => 'playing#verifyLoggedCharacter'
  get "/playing/enterWorld" => 'playing#enterWorld'

  # Routes pour interagir avec le PNJ
  get "/playing/talk/:id", to: 'playing#talk', as: 'talk_pnj'
  get "/playing/attack/:id", to: 'playing#attack_pnj', as: 'attack_pnj'
  post "/playing/perform_attack/:id", to: 'playing#perform_attack', as: 'perform_attack_pnj'
  post "/playing/finish_quest/:id", to: 'playing#finish_quest', as: 'finish_quest_pnj' # Changer en POST
  post "/playing/take_quest", to: 'playing#take_quest', as: 'take_quest'

  # ROOT ROUTE ('/', HOME PAGE)
  root "home#index"
end

app/models/Inventory.rb
class Inventory < ApplicationRecord
   belongs_to :characters, foreign_key: 'id_character'    
end

app/models/Inventory_item.rb
class InventoryItem < ApplicationRecord

    # has_and_belongs_to_many :spells

   belongs_to :inventories, foreign_key: 'id_inventory'
   belongs_to :items, foreign_key: 'id_item'
    
end

app/models/Item.rb
class Item < ApplicationRecord
   has_many :inventories_items
end

app/models/answer.rb
class Answer < ApplicationRecord
    belongs_to :enigmes, foreign_key: 'id_enigme'
    
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/character.rb
class Character < ApplicationRecord
  belongs_to :user, foreign_key: 'id_user'
  belongs_to :classes, foreign_key: 'id_class'
  has_many :character_quests, foreign_key: 'id_character'
  has_many :quests, through: :character_quests

  def className
    classes.name
  end
end

app/models/character_quest.rb
class CharacterQuest < ApplicationRecord
  belongs_to :character, foreign_key: 'id_character'
  belongs_to :quest, foreign_key: 'id_quest'
end

app/models/classes.rb
class Classes < ApplicationRecord

    # has_and_belongs_to_many :spells

    has_many :classes_spells
    has_many :spells, :through => :classes_spells
    
end

app/models/classesSpells.rb
class ClassesSpells < ApplicationRecord
    has_many :classes
    has_many :spells
end

app/models/enigme.rb
class Enigme < ApplicationRecord
    belongs_to :steps, foreign_key: 'id_step'
    has_many :answers
    
end

app/models/pnj.rb
class Pnj < ApplicationRecord
    has_many :pnj_steps
    has_many :steps, through: :pnj_steps
    has_many :pnj_spells
  end

app/models/pnj_spell.rb
class PnjSpell < ApplicationRecord
    belongs_to :pnjs, foreign_key: 'id_pnj'
    belongs_to :spells, foreign_key: 'id_spell'
     
 end

app/models/pnj_step.rb
class PnjStep < ApplicationRecord
   belongs_to :pnj, foreign_key: 'id_pnj'
   belongs_to :step, foreign_key: 'id_step'
 end

app/models/quest.rb
class Quest < ApplicationRecord
    has_many :character_quests, foreign_key: 'id_quest'
    has_many :characters, through: :character_quests
    has_many :steps
  end

app/models/spells.rb
class Spells < ApplicationRecord
    has_many :classes_spells
    has_many :pnjs_spells

end

app/models/step.rb
class Step < ApplicationRecord
    belongs_to :quests, foreign_key: 'id_quest'
    has_many :enigmes
    has_many :pnj_steps
    has_many :pnjs, through: :pnj_steps
end

app/models/stuff.rb
class Stuff < ApplicationRecord
    belongs_to :inventories, foreign_key: 'id_inventory'    
 end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 4 }
  validates :isAdmin, inclusion: { in: [true, false] }

  has_many :characters, foreign_key: 'id_user'
end

app/controllers/playing_controller.rb
class PlayingController < ApplicationController
  def verifyLoggedCharacter
    @character = Character.find_by(id: params[:id])
    if @character && @character.id_user == session[:user_id]
      session[:character_id] = @character.id
      redirect_to playing_enterWorld_path, notice: "Connected as : #{@character.name}"
    else
      redirect_to home_logged_path, alert: "Invalid character"
    end
  end

  def enterWorld
    @character = Character.find_by(id: session[:character_id])
    quest = Quest.find_by(id: 1)
    character_quest = CharacterQuest.find_by(id_character: @character.id, id_quest: quest.id)

    if character_quest.nil?
      @quest_available = true
      @pnj = nil
    else
      @pnj = Pnj.find_by(id: 2)
      @quest_available = false
    end
  end

  def take_quest
    @character = Character.find_by(id: session[:character_id])
    quest = Quest.find_by(id: 1)

    CharacterQuest.create(id_character: @character.id, id_quest: quest.id, advancement: 1)
    redirect_to playing_enterWorld_path, notice: "Quête prise avec succès !"
  end

  def talk
    @pnj = Pnj.find(params[:id])
    @character = Character.find_by(id: session[:character_id])

    # récup du résumé de la quête
    pnj_step = PnjStep.find_by(id_pnj: @pnj.id)
    step = Step.find_by(id: pnj_step.id_step)
    quest = Quest.find_by(id: step.id_quest)
    @conversation = quest.resume
  end

  def finish_quest
    @character = Character.find_by(id: session[:character_id])
    @pnj = Pnj.find(params[:id])

    # Trouver la quête associée au PNJ
    pnj_step = PnjStep.find_by(id_pnj: @pnj.id)
    step = Step.find_by(id: pnj_step.id_step)
    quest = Quest.find_by(id: step.id_quest)

    # Terminer la quête
    character_quest = CharacterQuest.find_by(id_character: @character.id, id_quest: quest.id)
    if character_quest
      character_quest.destroy
      redirect_to playing_enterWorld_path, notice: "Quête terminée avec succès !"
    else
      redirect_to playing_enterWorld_path, alert: "Quête non trouvée pour ce personnage."
    end
  end

  def attack_pnj
    @character = Character.find_by(id: session[:character_id])
    @pnj = Pnj.find(params[:id])
    render :attack_pnj
  end

  def perform_attack
    @character = Character.find_by(id: session[:character_id])
    @pnj = Pnj.find(params[:id])

    # combat simplifié (calcul avec hp et str)
    character_attack_power = @character.hp + @character.str
    pnj_attack_power = @pnj.hp + @pnj.str

    if character_attack_power > pnj_attack_power
      @result = "Vous avez gagné le combat contre #{@pnj.name}!"

      # Finir la quête en cas de victoire ( mais j'ai donné la possibilité de toujours pouvoir la reprendre x) )
      pnj_step = PnjStep.find_by(id_pnj: @pnj.id)
      step = Step.find_by(id: pnj_step.id_step)
      quest = Quest.find_by(id: step.id_quest)
      character_quest = CharacterQuest.find_by(id_character: @character.id, id_quest: quest.id)

      if character_quest
        character_quest.destroy
        flash[:notice] = "Vous avez terminé la quête avec succès en battant #{@pnj.name}!"
      end
    elsif pnj_attack_power > character_attack_power
      @result = "#{@pnj.name} a gagné le combat contre vous!"
    else
      @result = "Le combat s'est terminé par un match nul!"
    end

    render :attack_pnj
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/playing/enterWorld.html.erb
<div class="w-full flex flex-grow p-5 items-start h-fit justify-between">
  <% if @character %>
  <div class="flex flex-col gap-5 bg-slate-950 bg-opacity-70 rounded-xl hover:border-amber-500 hover:bg-opacity-80 w-fit p-5 border border-slate-700 transition-all duration-200">
    <div class="flex w-full items-center justify-between gap-2">
      <div class="flex flex-col min-w-fit">
        <img src="<%= @character.jpg %>" alt="<%= @character.name %>'s Profile Image" class="w-[95px] h-[95px]" />
      </div>
      <div class="flex flex-col w-full justify-between gap-1 text-xl pirata">
        <div class="flex gap-2">
          <p class="font-bold text-sky-500 min-w-fit">NAME :</p>
          <p class="font-normal text-center w-fit"><%= @character.name %></p>
        </div>
        <div class="flex gap-2">
          <p class="font-bold text-sky-500 min-w-fit">CLASS :</p>
          <p class="font-normal text-center w-fit"><%= @character.classes.name %></p>
        </div>
        <div class="flex gap-2">
          <p class="font-bold text-sky-500 min-w-fit">LEVEL :</p>
          <p class="font-normal text-center w-fit"><%= @character.lvl %></p>
        </div>
      </div>
    </div>
    
    <!-- Affichage des stats du personnage joueur -->
    <div class="flex flex-col w-full">
      <div class="flex gap-2 w-full justify-evenly">
        <div class="flex flex-col items-center justify-center min-w-[70px] max-w-[70px] p-2 bg-slate-400 bg-opacity-20 rounded-xl">
          <p class="pirata text-2xl text-[#786640]">STR</p>
          <p class="font-bold p-2"><%= @character.str %></p>
        </div>
        <div class="flex flex-col items-center justify-center min-w-[70px] max-w-[70px] p-2 bg-slate-400 bg-opacity-20 rounded-xl">
          <p class="pirata text-2xl text-red-400">INT</p>
          <p class="font-bold p-2"><%= @character.intel %></p>
        </div>
        <div class="flex flex-col items-center justify-center min-w-[70px] max-w-[70px] p-2 bg-slate-400 bg-opacity-20 rounded-xl">
          <p class="pirata text-2xl text-green-400">AGI</p>
          <p class="font-bold p-2"><%= @character.agi %></p>
        </div>
        <div class="flex flex-col items-center justify-center min-w-[70px] max-w-[70px] p-2 bg-slate-400 bg-opacity-20 rounded-xl">
          <p class="pirata text-2xl text-blue-500">EXP</p>
          <p class="font-bold p-2"><%= @character.xp %></p>
        </div>
      </div>
    </div>
  </div>

  <% if @quest_available %>
    <!-- Affichage de la possibilité de prendre la quête -->
    <div class="flex flex-col gap-5 bg-slate-950 bg-opacity-70 rounded-xl hover:border-amber-500 hover:bg-opacity-80 w-fit p-5 border border-slate-700 transition-all duration-200">
      <div class="flex flex-col min-w-fit gap-2">
        <p class="text-white pirata text-2xl">Une quête est disponible !</p>
        <%= form_with(url: take_quest_path, method: :post) do %>
          <%= submit_tag 'Prendre la quête', class: "w-full bg-green-500 p-2 rounded text-center text-sm pirata hover:bg-green-600 transition-all duration-200" %>
        <% end %>
      </div>
    </div>
  <% end %>

  <!-- Affichage du PNJ -->
  <% if @pnj %>
  <div class="flex flex-col gap-5 bg-slate-950 bg-opacity-70 rounded-xl hover:border-amber-500 hover:bg-opacity-80 w-fit p-5 border border-slate-700 transition-all duration-200">
    <div class="flex w-full items-center justify-between gap-2">
      <div class="flex flex-col min-w-fit">
        <img src="<%= @pnj.jpg %>" alt="<%= @pnj.name %>'s Profile Image" class="w-[95px] h-[95px]" />
      </div>
      <div class="flex flex-col w-full justify-between gap-1 text-xl pirata">
        <div class="flex gap-2">
          <p class="font-bold text-sky-500 min-w-fit">NAME :</p>
          <p class="font-normal text-center w-fit"><%= @pnj.name %></p>
        </div>
        <div class="flex gap-2">
          <p class="font-bold text-sky-500 min-w-fit">Main Stat :</p>
          <p class="font-normal text-center w-fit"><%= @pnj.mainStat %></p>
        </div>
        <div class="flex gap-2">
          <p class="font-bold text-sky-500 min-w-fit">LEVEL :</p>
          <p class="font-normal text-center w-fit"><%= @pnj.lvl %></p>
        </div>
      </div>
    </div>
    
    <div class="flex flex-col w-full">
      <div class="flex gap-2 w-full justify-evenly">
        <div class="flex flex-col items-center justify-center min-w-[70px] max-w-[70px] p-2 bg-slate-400 bg-opacity-20 rounded-xl">
          <p class="pirata text-2xl text-[#786640]">STR</p>
          <p class="font-bold p-2"><%= @pnj.str %></p>
        </div>
        <div class="flex flex-col items-center justify-center min-w-[70px] max-w-[70px] p-2 bg-slate-400 bg-opacity-20 rounded-xl">
          <p class="pirata text-2xl text-red-400">INT</p>
          <p class="font-bold p-2"><%= @pnj.intel %></p>
        </div>
        <div class="flex flex-col items-center justify-center min-w-[70px] max-w-[70px] p-2 bg-slate-400 bg-opacity-20 rounded-xl">
          <p class="pirata text-2xl text-green-400">AGI</p>
          <p class="font-bold p-2"><%= @pnj.agi %></p>
        </div>
      </div>
    </div>

    <div class="flex gap-2 items-center justify-center w-full">
      <%= link_to 'Talk', talk_pnj_path(@pnj), class: "w-3/6 bg-green-500 p-2 rounded text-center text-sm pirata hover:bg-green-600 transition-all duration-200" %>
      
      <%= form_with(url: perform_attack_pnj_path(@pnj), method: :post, class: "w-3/6") do %>
        <%= submit_tag 'Attack', class: "bg-red-500 p-2 rounded text-center text-sm pirata hover:bg-red-600 transition-all duration-200 w-full" %>
      <% end %>
    </div>
  </div>
  <% end %>
<% end %>
</div>

<div class="w-full flex items-center justify-center">
  <% if flash[:notice] %>
    <div class="p-2 rounded toastSuccess mb-20">
      <%= flash[:notice] %>
    </div>
  <% elsif flash[:alert] %>
    <div class="p-2 rounded toastError mb-20">
      <%= flash[:alert] %>
    </div>
  <% end %>
</div>

<form class="p-5 w-full h-fit flex justify-end items-center" action="<%= url_for(controller: 'auth', action: 'logout') %>" method="post">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <input type="submit" class="text-sm cursor-pointer w-fit flex items-center justify-center bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded flex items-center transition-all duration 200" value="LOGOUT"></input>
</form>

app/views/playing/finish_quest_success.html.erb
<div class="w-full flex flex-col items-center justify-center h-screen">
  <div class="flex flex-col gap-5 bg-slate-950 bg-opacity-70 rounded-xl p-5 border border-slate-700 transition-all duration-200">
    <h1 class="text-4xl font-bold text-sky-500 pirata">Quête terminée avec succès!</h1>
    <p class="text-white pirata text-2xl">Vous avez terminé la quête avec succès.</p>
    <%= link_to 'Retourner à l\'accueil', playing_enterWorld_path, class: "bg-green-500 p-2 rounded text-center text-sm pirata hover:bg-green-600 transition-all duration-200" %>
  </div>
</div>

app/views/playing/talk.html.erb
<div class="w-full flex flex-col flex-grow items-start h-fit justify-between peonQuest">
  <div class="w-full flex flex-col flex-grow p-5 bg-black bg-opacity-50">
    <div class="w-full flex h-fit items-start justify-between flex-grow">
      <% if @character %>
        <div class="flex flex-col gap-5 bg-slate-950 bg-opacity-70 rounded-xl hover:border-amber-500 hover:bg-opacity-80 w-fit p-5 border border-slate-700 transition-all duration-200">
          <div class="flex w-full items-center justify-between gap-2">
            <div class="flex flex-col min-w-fit">
              <img src="<%= @character.jpg %>" alt="<%= @character.name %>'s Profile Image" class="w-[95px] h-[95px]" />
            </div>
            <div class="flex flex-col w-full justify-between gap-1 text-xl pirata">
              <div class="flex gap-2">
                <p class="font-bold text-sky-500 min-w-fit">NAME :</p>
                <p class="font-normal text-center w-fit"><%= @character.name %></p>
              </div>
              <div class="flex gap-2">
                <p class="font-bold text-sky-500 min-w-fit">CLASS :</p>
                <p class="font-normal text-center w-fit"><%= @character.classes.name %></p>
              </div>
              <div class="flex gap-2">
                <p class="font-bold text-sky-500 min-w-fit">LEVEL :</p>
                <p class="font-normal text-center w-fit"><%= @character.lvl %></p>
              </div>
            </div>
          </div>
          <div class="flex flex-col w-full">
            <div class="flex gap-2 w-full justify-evenly">
              <div class="flex flex-col items-center justify-center min-w-[70px] max-w-[70px] p-2 bg-slate-400 bg-opacity-20 rounded-xl">
                <p class="pirata text-2xl text-green-600">HP</p>
                <p class="font-bold p-2"><%= @character.hp %></p>
              </div>
              <div class="flex flex-col items-center justify-center min-w-[70px] max-w-[70px] p-2 bg-slate-400 bg-opacity-20 rounded-xl">
                <p class="pirata text-2xl text-[#786640]">STR</p>
                <p class="font-bold p-2"><%= @character.str %></p>
              </div>
              <div class="flex flex-col items-center justify-center min-w-[70px] max-w-[70px] p-2 bg-slate-400 bg-opacity-20 rounded-xl">
                <p class="pirata text-2xl text-red-400">INT</p>
                <p class="font-bold p-2"><%= @character.intel %></p>
              </div>
              <div class="flex flex-col items-center justify-center min-w-[70px] max-w-[70px] p-2 bg-slate-400 bg-opacity-20 rounded-xl">
                <p class="pirata text-2xl text-green-400">AGI</p>
                <p class="font-bold p-2"><%= @character.agi %></p>
              </div>
              <div class="flex flex-col items-center justify-center min-w-[70px] max-w-[70px] p-2 bg-slate-400 bg-opacity-20 rounded-xl">
                <p class="pirata text-2xl text-blue-500">EXP</p>
                <p class="font-bold p-2"><%= @character.xp %></p>
              </div>
            </div>
          </div>
        </div>
      <% end %>

      <!-- Affichage de la discussion avec le PNJ -->
      <% if @pnj %>
        <div class="flex flex-col gap-5 bg-slate-950 bg-opacity-70 rounded-xl hover:border-amber-500 hover:bg-opacity-80 w-fit p-5 border border-slate-700 transition-all duration-200">
          <div class="flex w-full items-center justify-between gap-2">
            <div class="flex flex-col min-w-fit">
              <img src="<%= @pnj.jpg %>" alt="<%= @pnj.name %>'s Profile Image" class="w-[95px] h-[95px]" />
            </div>
            <div class="flex flex-col w-full justify-between gap-1 text-xl pirata">
              <div class="flex gap-2">
                <p class="font-bold text-sky-500 min-w-fit">NAME :</p>
                <p class="font-normal text-center w-fit"><%= @pnj.name %></p>
              </div>
              <div class="flex gap-2">
                <p class="font-bold text-sky-500 min-w-fit">Main Stat :</p>
                <p class="font-normal text-center w-fit"><%= @pnj.mainStat %></p>
              </div>
              <div class="flex gap-2">
                <p class="font-bold text-sky-500 min-w-fit">LEVEL :</p>
                <p class="font-normal text-center w-fit"><%= @pnj.lvl %></p>
              </div>
            </div>
          </div>
          <div class="flex flex-col w-full">
            <div class="flex gap-2 w-full justify-evenly">
              <div class="flex flex-col items-center justify-center min-w-[70px] max-w-[70px] p-2 bg-slate-400 bg-opacity-20 rounded-xl">
                <p class="pirata text-2xl text-[#786640]">STR</p>
                <p class="font-bold p-2"><%= @pnj.str %></p>
              </div>
              <div class="flex flex-col items-center justify-center min-w-[70px] max-w-[70px] p-2 bg-slate-400 bg-opacity-20 rounded-xl">
                <p class="pirata text-2xl text-red-400">INT</p>
                <p class="font-bold p-2"><%= @pnj.intel %></p>
              </div>
              <div class="flex flex-col items-center justify-center min-w-[70px] max-w-[70px] p-2 bg-slate-400 bg-opacity-20 rounded-xl">
                <p class="pirata text-2xl text-green-400">AGI</p>
                <p class="font-bold p-2"><%= @pnj.agi %></p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>

    <!-- Affichage de la conversation -->
    <div class="flex w-full justify-end px-2">
      <div class="flex flex-col gap-5 bg-slate-950 bg-opacity-70 max-w-[450px] h-fit rounded-xl p-5 border border-slate-700 transition-all duration-200 text-justify">
        <h2 class="text-4xl font-bold text-sky-500 pirata"><%= @pnj.name %> :</h2>
        <p class="text-white pirata text-2xl"><%= @conversation %></p>
        
        <!-- Boutons pour finir la quête ou attaquer le PNJ -->
        <div class="flex gap-4 mt-4">
          <%= form_with(url: finish_quest_pnj_path(@pnj), method: :post) do %>
            <%= submit_tag 'Serrer la main du Péon', class: "bg-green-500 p-2 rounded text-center text-sm pirata hover:bg-green-600 transition-all duration-200" %>
          <% end %>
          <%= form_with(url: perform_attack_pnj_path(@pnj), method: :post) do %>
            <%= submit_tag 'Attaquer', class: "bg-red-500 p-2 rounded text-center text-sm pirata hover:bg-red-600 transition-all duration-200" %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="w-full flex items-center justify-center">
      <% if flash[:notice] %>
        <div class="p-2 rounded toastSuccess mb-20">
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="p-2 rounded toastError mb-20">
          <%= flash[:alert] %>
        </div>
      <% end %>
    </div>

    <form class="p-5 w-full h-fit flex justify-end items-center" action="<%= url_for(controller: 'auth', action: 'logout') %>" method="post">
      <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
      <input type="submit" class="text-sm cursor-pointer w-fit flex items-center justify-center bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded flex items-center transition-all duration 200" value="LOGOUT"></input>
    </form>
  </div>
</div>